### ISSUE TITLE
Sidebar for Admin Dashboard is not rendering.

### ISSUE THREAD

**Issue by Diparshan-1** [ShubhamShrestha60/ProjectVroom#2]
Error with either the JSX or CSS file. Code needs to get checked.

    <div className="sidebar">
      <div className="sidebar__top">
        <h2>
          <span>
            <i className="ri-taxi-line"></i>
          </span>{" "}
          Vroom
        </h2>
      </div>

      <div className="sidebar__content">
        <div className="menu">
          <ul className="nav__list">
            {navLinks.map((item, index) => (
              <li className="nav__item" key={index}>
                <NavLink
                  to={item.path}
                  className={(navClass) =>
                    navClass.isActive ? "nav__active nav__link" : "nav__link"
                  }
                >
                  <i className={item.icon}></i>
                  {item.display}
                </NavLink>
              </li>
            ))}
          </ul>
        </div>

        <div className="sidebar__bottom">
          <span>
            <i className="ri-logout-circle-r-line"></i> Logout
          </span>
        </div>
      </div>
    </div>
  );
};

export default Sidebar;`

**Comment by Solvedsplash** [comment]
Thanks for flagging! I will investigating the sidebar rendering issue
