### ISSUE TITLE
Error handling for Log in Page

### ISSUE THREAD

**Issue by ShubhamShrestha60** [ShubhamShrestha60/ProjectVroom#3]
Hello Team, I think that the Login page's error handling can be much better. I feel the need of adding a pop up message for successful login for the better user experience. @Pratik100-source 
`    <label htmlFor="my-email" style={styles.label}>
      Email
    </label>
    <input id="Email" type="Email" style={styles.email} name="email" value={formData.email} onChange={handleChange} />

    <label htmlFor="my-password" style={styles.label}>
      Password
    </label>
    <input id="my-password" type="password" style={styles.password} name="password" value={formData.password} onChange={handleChange} />

    <button style={styles.button}>Login</button>

    <p style={styles.forgotPassword}>Forget Password?</p>

    <p style={styles.signUp}>
      Don't have an account yet? <span style={{ color: "#5CB3FF" }}><Link to="/signup">Sign up</Link></span>
    </p>
  </form>
</div>`

**Comment by Pratik100-source** [comment]
Working on it

**Comment by Pratik100-source** [comment]
The problem is solved .. you can check it shubham

**Comment by ShubhamShrestha60** [comment]
just checked it Pratik. Good work
